// DON'T EDIT THE CODE.
// This code generated by lib localization.

import 'package:example/src/locale/example_locale.dart';
import 'package:flutter/material.dart';

class ExampleLocaleDelegate extends LocalizationsDelegate<ExampleLocale> {
  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<ExampleLocale> load(Locale locale) async {
    return ExampleLocale(locale.languageCode);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<ExampleLocale> old) => false;
}
