// DON'T EDIT THE CODE.
// This code generated by oni locale library.

import 'package:oni_locale/oni.dart';

class ExampleResource extends OniResource {
  ExampleResource(String? languageCode) : super(languageCode);
  
  @override
  Map<String, Map<String, String>> get resources => {
    'bookCollection': {
      'id': 'buku',
      'en': 'book',
    },
    'chairCollection': {
      'id': 'kursi %s',
      'en': 'chair %s',
    },
  };
}
