// DON'T EDIT THE CODE.
// This code generated by oni locale library.

import 'package:oni_locale/oni.dart';
import 'package:example/src/locale/example_resource.dart';

class ExampleLocale extends OniLocale {
  ExampleLocale([String? languageCode]) : super(languageCode);
  
  String get bookCollection {
    return resource.get('bookCollection');
  }
  
  String chairCollection(dynamic s0) {
    return resource.get('chairCollection', args: [s0]);
  }
  
  @override
  OniResource get resource {
    return ExampleResource(languageCode);
  }
}
