// DON'T EDIT THE CODE.
// This code generated by lib localization.

import 'package:oni_locale/main.dart';

class ExampleLocaleResource extends OniResource {
  ExampleLocaleResource(String? languageCode) : super(languageCode);

  @override
  Map<String, Map<String, String>> get resources => {
    'bookCollection': {
      'id': 'buku',
      'en': 'book',
    }
  };
}
