// DON'T EDIT THE CODE.
// This code generated by oni locale library.

import 'package:flutter/widgets.dart';
import 'package:example/src/locale/example_locale.dart';

class ExampleDelegate extends LocalizationsDelegate<ExampleLocale> {
  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<ExampleLocale> load(Locale locale) async {
    return ExampleLocale(locale.languageCode);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<ExampleLocale> old) => false;
}
